---
os_ntopng_extra_packages:
  FreeBSD: []
  OpenBSD: []
  Debian:
    - pfring
    - ntopng-data
    - net-tools
  RedHat:
    - pfring
    - ntopng-data
    - net-tools
ntopng_extra_packages: "{{ os_ntopng_extra_packages[ansible_os_family] }}"
ntopng_config: |
  {% if ansible_os_family == 'Debian' %}
  -e=
  --data-dir={{ ntopng_db_dir }}
  --user={{ ntopng_user }}
  {% endif %}
  --http-port={{ project_ntopng_listen_address }}:3000
  --disable-autologout
  --disable-login={{ project_ntopng_disable_login }}
  --community
  --interface={{ project_ntopng_interface }}
apt_repo_keys_to_add:
  - http://packages.ntop.org/apt-stable/ntop.key
apt_repo_to_add:
  - deb http://packages.ntop.org/apt-stable/{{ ansible_distribution_version }}/ x64/
  - deb http://packages.ntop.org/apt-stable/{{ ansible_distribution_version }}/ all/
redhat_repo_extra_packages:
  - epel-release
redhat_repo:
  epel:
    mirrorlist: "http://mirrors.fedoraproject.org/mirrorlist?repo=epel-{{ ansible_distribution_major_version }}&arch={{ ansible_architecture }}"
    gpgcheck: yes
    enabled: yes
  ntop:
    baseurl: http://packages.ntop.org/centos-stable/$releasever/$basearch/
    enabled: yes
    gpgcheck: yes
    gpgkey: http://packages.ntop.org/centos-stable/RPM-GPG-KEY-deri
  ntop_noarch:
    baseurl: http://packages.ntop.org/centos-stable/$releasever/noarch/
    enabled: yes
    gpgcheck: yes
    gpgkey: http://packages.ntop.org/centos-stable/RPM-GPG-KEY-deri

netplan_config: "{{ project_netplan_config }}"
netplan_force_flush_handlers: yes

os_argus_flags:
  OpenBSD: "-F {{ argus_config_file }}"
  FreeBSD: |
    argus_flags='-F {{ argus_config_file }}'
    argus_pidfile='/var/run/argus.{{ ansible_default_ipv4.device | default(omit) }}.*.pid'
  Debian: |
    ARGUS_OPTIONS="-F {{ argus_config_file }}"
  RedHat: |
    ARGUS_OPTIONS="-F {{ argus_config_file }}"
argus_flags: "{{ os_argus_flags[ansible_os_family] }}"
argus_config: |
  ARGUS_FLOW_TYPE="Bidirectional"
  ARGUS_FLOW_KEY="CLASSIC_5_TUPLE"
  {% if ansible_os_family != 'Debian' and ansible_os_family != 'RedHat' %}
  # XXX the unit file expects the command not to fork
  ARGUS_DAEMON=yes
  {% endif %}
  ARGUS_ACCESS_PORT=561
  ARGUS_BIND_IP="127.0.0.1"
  ARGUS_INTERFACE={{ project_ntopng_interface }}
  ARGUS_GO_PROMISCUOUS=yes
  ARGUS_SETUSER_ID={{ argus_user }}
  ARGUS_SETGROUP_ID={{ argus_group }}
  ARGUS_FLOW_STATUS_INTERVAL=60
  ARGUS_MAR_STATUS_INTERVAL=300
  ARGUS_DEBUG_LEVEL=1
  ARGUS_FILTER="ip"
  ARGUS_SET_PID=yes
  ARGUS_PID_PATH=/var/run
  {% if ansible_os_family == 'FreeBSD' or ansible_os_family == 'OpenBSD' %}
  # XXX enable only if ansible_os_family is either FreeBSD or OpenBSD.
  # Ubuntu package is built without SASL (Build without sasl for now)
  # http://changelogs.ubuntu.com/changelogs/pool/universe/a/argus/argus_3.0.8.2-1/changelog
  ARGUS_MIN_SSF=40
  ARGUS_MAX_SSF=128
  {% endif %}
