---

- name: trombik.hostname
- name: trombik.hosts
- name: trombik.sudo
- name: trombik.zsh
- name: trombik.vim
- name: trombik.tmux
- name: trombik.apt_repo
- name: trombik.ntopng
- name: trombik.netplan
- name: trombik.netstart
- name: trombik.argus
- name: trombik.argus_clients
