---
all:
  hosts:
    dumbhub.i.trombik.org:
      ansible_host: 10.1.5.110

  children:
    dumbhub:
      hosts:
        dumbhub.i.trombik.org:
    prod_credentials:
      children:
        dumbhub:
    prod:
      children:
        dumbhub:
