---

- name: Install squid
  apt:
    name: "{{ squid_package }}"
    state: present

- name: Create default for squid init script
  template:
    src: Debian.default.j2
    dest: "/etc/default/{{ squid_package }}"
    validate: sh -n %s
    backup: yes
  notify: Restart squid

- name: Enable squid_service
  service:
    name: "{{ squid_service }}"
    enabled: yes
