---
- hosts: dumbhub
  become: yes
  become_method: sudo
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"

  pre_tasks:
    - debug: var=hostvars[inventory_hostname]
  roles:
    - role: trombik.hosts
    - role: trombik.hostname
    - role: trombik.sudo
    - role: trombik.apt_repo
      when: ansible_os_family == 'Debian'
    - role: trombik.tmux
    - role: trombik.vim
    - role: trombik.zsh
    - role: trombik.netplan
      when: ansible_os_family == 'Debian'
    - role: trombik.ntopng
    - role: trombik.argus
    - role: trombik.argus_clients
    - role: trombik.rastream
    - role: trombik.net_snmp
    - role: trombik.dumpcap
  vars:
