---
- hosts: peer
  become: yes
  become_method: sudo
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"

  pre_tasks:
    - debug: var=hostvars[inventory_hostname]
  roles:
    - role: trombik.netstart
  vars:
    netstart_config:
      - name: em2
        content: |
          192.168.20.100/24
          up
